### ISSUE TITLE
Flashing Screen

### ISSUE THREAD

**Issue by theopcoder** [Project-Prism/Prism-OS#13]
Build: 666cf22acff3472c7ee9c1579b2b1fe4ca054b8e
Issue: Flashing/unusable screen

Video: 

https://user-images.githubusercontent.com/58401646/126102492-3c0d851e-c09f-47e8-a238-31ded80aa789.mp4

**Comment by deaddlocust** [comment]
We are aware of this and it is one of the top priorities for this project. For whatever reason, rendering is slow.
