### ISSUE TITLE
I get this error when trying to boot up the latest release of the OS on vmware

### ISSUE THREAD

**Issue by Twingamerdudes** [Project-Prism/Prism-OS#32]
So when I try to boot up the OS in vmware, it gives this cpu exception  x06 error. Does anyone know why this is happing
![Screenshot (1119)](https://user-images.githubusercontent.com/81382687/164110822-0410a3bc-97bb-4aca-8056-f1fa734b1aab.png)

**Comment by asterd-og** [comment]
the canvas doesn't works on vmware, boot it on virtual box

**Comment by terminal-cs** [comment]
Hello! Prism does not work on VMware right now because of an issue with the compiler, you should use vbox instead.

**Comment by Twingamerdudes** [comment]
alr, thanks
