### ISSUE TITLE
Latest release build wont load (VMWare and VBox)

### ISSUE THREAD

**Issue by GoldenretriverYT** [Project-Prism/Prism-OS#51]
#### Describe the bug
The latest release does not load in either VMWare or VBox. It gets stuck on the PrismOS icon.

#### To Reproduce
Download ISO and execute in VM

#### Expected behavior
Should start up

#### Additional context
I believe this is due to the virtual hard drive not being partioned, but that should be a functionality within the OS on first time startup

**Comment by GoldenretriverYT** [comment]
I am unsure what the main boot screen is, but the only thing I get to see is the black screen with the centered PrismOS icon

**Comment by terminal-cs** [comment]
Yes, that is the boot screen. I am not sure exactly why VMware tends to crash more often, how much RAM have you allocated to the VM?

**Comment by GoldenretriverYT** [comment]
256mb in both VMWare and VBox. As I already said, it has nothing to do with VMWare as the exact same happens in VBox

**Comment by terminal-cs** [comment]
It works for me, and others aswell. This is most likely a cosmos issue

**Comment by GoldenretriverYT** [comment]
cosmos moment lol

**Comment by terminal-cs** [comment]
Indeed

**Comment by EnterTheVoid-x86** [comment]
Works for me on VMWare after setting the amount of ram to 1GB.

**Comment by terminal-cs** [comment]
I will close this as +/- fixed, as cosmos bugs are out of the scope of this project.

**Comment by GoldenretriverYT** [comment]
> Works for me on VMWare after setting the amount of ram to 1GB.

I just checked and this is true.
@terminal-cs do you have your Cosmos Testing VM that is created to Cosmos edited to use more than 256mb?

**Comment by terminal-cs** [comment]
> > Works for me on VMWare after setting the amount of ram to 1GB.
> 
> I just checked and this is true.
> @terminal-cs do you have your Cosmos Testing VM that is created by Cosmos edited to use more than 256mb?

Nope
