### ISSUE TITLE
TO-DO: Create API documentation.

### ISSUE THREAD

**Issue by terminal-cs** [Project-Prism/Prism-OS#54]
Need to create in-depth documentation html pages for every class
Can use existing inline documentation from code but it is recomended to also add extra notes

- [x] PrismAudio
- [ ] PrismBinary
- [ ] PrismFilesystem
- [x] PrismGraphics
- [x] PrismNetwork
- [x] PrismRuntime
- [x] PrismTools

**Comment by StiglCZ** [comment]
Okay, ill help
