### ISSUE TITLE
Pls Fix The WebDemo for Chrome

### ISSUE THREAD

**Issue by EndermanPC** [Project-Prism/Prism-OS#56]
WebDemo show me this and i can't use prismOS, (my Browser is Chrome)
![image](https://user-images.githubusercontent.com/88751712/198318201-70cb2f94-97ce-44eb-bebd-b2879c569453.png)

**Comment by terminal-cs** [comment]
Hello,
The server maintainer is responsible for maintaining the web demo and they have not yet fixed it. I will close this issue as soon as they do

**Comment by RaphMar2021** [comment]
We can close this issue because the website has been updated, and there is no web demo on it.
