### ISSUE TITLE
I can't compile this OS due to package version incongruence.

### ISSUE THREAD

**Issue by aleOS2** [Project-Prism/Prism-OS#61]
#### Describe the bug
Hi, When i try to compile this project i receive 11 errors, all similar to: "Detected package downgrade: Cosmos.System2 from 0.1.0-localbuild20221024075635 to 0.1.0-localbuild20220209054647. Reference the package directly from the project to select a different version." in various files. I have tried to Manage nuget but i can't reached to fix that.

#### To Reproduce
I guess using the last Dev kit + VS 2022 and start this project.
#### Expected behavior
Reach to compile and boot.
#### Screenshots
![image](https://user-images.githubusercontent.com/65780895/200167102-7627fefc-a256-443e-b063-0699e71c3088.png)

#### Additional context
Is all in the screenshot.

Thanks for anyone replyes.

**Comment by RaphMar2021** [comment]
Upgrade DevKit version

**Comment by aleOS2** [comment]
I have installed the DevKit the day before yesterday, but ok i will try.
Thanks

Il dom 6 nov 2022, 12:14 Raphael ***@***.***> ha scritto:

**Comment by terminal-cs** [comment]
Hi,
This is an issue with how cosmos is made, they do not publish packages so we need to keep the packages updated manualy,I will fix it in a bit

**Comment by terminal-cs** [comment]
Older installs should work with new versions

**Comment by terminal-cs** [comment]
fixed.

**Comment by aleOS2** [comment]
I have tried this new version, but unlucky doesn't seems fixed.
![image](https://user-images.githubusercontent.com/65780895/200360451-ea6f8d42-0082-482e-a20d-32846792737a.png)

**Comment by terminal-cs** [comment]
fixed
