### ISSUE TITLE
ISOFiles does not work.

### ISSUE THREAD

**Issue by bytespacegames** [Project-Prism/Prism-OS#71]
#### Describe the bug
Files placed in IsoFiles are not included in the compilation of the ISO.

#### To Reproduce
Go on Latest UserKit, include a file in ISOFiles, and compile. It was not recognized by my code, and when looking through the ISO with 7zip, the file wasn't located there either.

#### Expected behavior
The file is included in the iso upon compilation, and can be read by a VFS.

**Comment by GoldenretriverYT** [comment]
Thats a Cosmos bug and not PrismOS

**Comment by bytespacegames** [comment]
> Thats a Cosmos bug and not PrismOS

Shit wrong project lmfao

**Comment by GoldenretriverYT** [comment]
lol
