### ISSUE TITLE
VBox doesn't work

### ISSUE THREAD

**Issue by DevBadger10** [Project-Prism/Prism-OS#72]
#### Describe the bug
VBox throws this error: 
![image](https://user-images.githubusercontent.com/104037142/228163738-fd118d7b-b84b-45e0-8b9e-4c88de81f172.png)

#### To Reproduce
Use it in VBox
#### Expected behavior
For it to work.
#### Screenshots

![image](https://user-images.githubusercontent.com/104037142/228163766-482a1b90-8d15-40a0-a3b6-ec060854ae56.png)

#### Additional context
I know that sometimes Cosmos doesnt work with VBox its just that I dont wanna get VMWare

**Comment by terminal-cs** [comment]
This is a non-issue, Cosmos broke VBE so we have no choice but yo use VMWare graphics drivers. You can set vbox to use it aswell and it will work
